version: 0.0
os: linux
files:
  - source: /personal
    destination: /var/www/romanch.uk/codedeploy
  - source: /conf/puma.service
    destination: /etc/systemd/system/puma.service
  - source: /conf/romanch.uk.conf
    destination: /etc/nginx/conf.d/romanch.uk.conf
  file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/romanch.uk/codedeploy
    owner: ubuntu
    group: ubuntu
    pattern: "**"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy_scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: deploy_scripts/bundle_install.sh
      runas: ubuntu
    - location: deploy_scripts/compile_assets.sh
      runas: ubuntu
    - location: deploy_scripts/migrate.sh
      runas: ubuntu

  ApplicationStart:
    - location: deploy_scripts/application_start.sh
      runas: ubuntu