version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ubuntu/codedeploy/romanch.uk/app
  - source: /config
    destination: /home/ubuntu/codedeploy/romanch.uk/config
  - source: /Gemfile
    destination: /home/ubuntu/codedeploy/romanch.uk/Gemfile
  - source: /Gemfile.lock
    destination: /home/ubuntu/codedeploy/romanch.uk/Gemfile.lock
  - source: /db
    destination: /home/ubuntu/codedeploy/romanch.uk/db
    

file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/romanch.uk/codedeploy
    owner: ubuntu
    group: ubuntu
    pattern: "**"
    mode: 775
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      runas: ubuntu