version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ubuntu/codedeploy/romanch.uk/app
  - source: /config
    destination: /home/ubuntu/codedeploy/romanch.uk/config
  - source: ./Gemfile
    destination: /home/ubuntu/codedeploy/romanch.uk
  - source: ./Gemfile.lock
    destination: /home/ubuntu/codedeploy/romanch.uk
  - source: /db
    destination: /home/ubuntu/codedeploy/romanch.uk/db
  - source: /lib
    destination: /home/ubuntu/codedeploy/romanch.uk/lib
  - source: /public
    destination: /home/ubuntu/codedeploy/romanch.uk/public
  - source: /vendor
    destination: /home/ubuntu/codedeploy/romanch.uk/vendor
  - source: /bin
    destination: /home/ubuntu/codedeploy/romanch.uk/bin
  - source: ./config.ru
    destination: /home/ubuntu/codedeploy/romanch.uk
  - source: ./Rakefile
    destination: /home/ubuntu/codedeploy/romanch.uk
  - source: ./.ruby-version
    destination: /home/ubuntu/codedeploy/romanch.uk
  - source: /deploy_scripts
    destination: /home/ubuntu/codedeploy/romanch.uk/deploy_scripts
  - source: /public
    destination: /home/ubuntu/codedeploy/romanch.uk/public
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/ubuntu/codedeploy
    owner: ubuntu
    group: ubuntu
    pattern: "**"
    mode: 775
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      runas: ubuntu
  ValidateService:
    - location: deploy_scripts/cleanup.sh
      runas: ubuntu