version: 0.0
os: linux
files:
  - source: /personal
    destination: /var/www/romanch.uk/codedeploy
  # - source: /conf/puma.service
  #   destination: /etc/systemd/system/
  # - source: /conf/sidekiq.service
  #   destination: /etc/systemd/system/
  - source: /conf/romanch.uk.conf
    destination: /etc/nginx/conf.d/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/romanch.uk/codedeploy
    owner: ubuntu
    group: ubuntu
    pattern: "**"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy_scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      runas: ubuntu