version: '3'
services:
  postgres:
    image: postgis/postgis:14-3.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
  redis:
    image: redis:7.0.4
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30