source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg"

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', github: 'puma/puma'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
gem "cssbundling-rails", "~> 1.1"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# # Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis"
gem "hiredis"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem 'gutentag'
gem 'simple_form', github: 'heartcombo/simple_form', branch: 'main'
gem 'aws-sdk-s3', require: false
gem 'down', require: false

gem 'aws-sdk-cognitoidentityprovider'

gem 'cognito_token_verifier', github: 'rromanchuk/cognito_token_verifier', require: false
gem "lograge"
gem 'sitemap_generator'
gem 'oj', require: false
gem 'friendly_id'
gem 'jwt'
gem "view_component"
gem "awesome_print"
gem "oauth2"
gem 'pg_search'
gem "auto_strip_attributes"
gem 'high_voltage'
gem "action_policy"
gem "sentry-ruby"
gem "sentry-rails"

gem "redis-client"
gem 'dynamoid'

gem 'sidekiq'
#gem 'sidekiq-cron', github: 'ondrejbartas/sidekiq-cron'
gem "anycable-rails", "~> 1.1"
gem "anycable-rails-jwt"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'bullet'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
  gem 'rails_real_favicon'
  

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "mocha"
end



gem "pagy", "~> 5.10"
gem 'activerecord-postgis-adapter'
gem 'httparty'
gem "pghero"
gem 'whenever', require: false
gem 'aws-sdk-textract', require: false
gem 'marginalia'
gem 'ox'