default: &default
  adapter: postgis
  schema_search_path: public, postgis
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_development
    host: localhost
    migrations_paths: db/ryan_romanchuk
  legacy:
    <<: *default
    database: personal_development
    #username: postgres
    host: localhost
  wx:
    <<: *default
    database: wx_development
    host: localhost
    migrations_paths: db/wx
  ro:
    <<: *default
    database: ro_development
    host: localhost
    migrations_paths: db/ro

test:
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_test
    username: postgres
    host: localhost
    migrations_paths: db/ryan_romanchuk
  legacy:
    <<: *default
    database: personal_test
    username: postgres
    host: localhost
  wx:
    <<: *default
    database: wx_test
    username: postgres
    host: localhost
    migrations_paths: db/wx
  ro:
    <<: *default
    database: ro_test
    username: postgres
    host: localhost
    migrations_paths: db/ro

production:
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/ryan_romanchuk
  legacy:
    <<: *default
    database: personal_production
    username: personal
    #password: <%= ENV["PERSONAL_DATABASE_PASSWORD"] %>
  wx:
    <<: *default
    database: wx_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/wx
  ro:
    <<: *default
    database: ro_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/ro
