default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000


development:
  primary:
    <<: *default
    database: personal_development
    #username: postgres
    host: localhost
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_development
    host: localhost
    migrations_paths: db/ryan_romanchuk
  wx:
    <<: *default
    database: wx_development
    host: localhost
    migrations_paths: db/wx
  ro:
    <<: *default
    database: ro_development
    host: localhost
    migrations_paths: db/ro
  cache:
    adapter: sqlite3
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache
  cable:
    adapter: sqlite3
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable

test:
  primary:
    <<: *default
    database: personal_test
    username: postgres
    host: localhost
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_test
    username: postgres
    host: localhost
    migrations_paths: db/ryan_romanchuk
  wx:
    <<: *default
    database: wx_test
    username: postgres
    host: localhost
    migrations_paths: db/wx
  ro:
    <<: *default
    database: ro_test
    username: postgres
    host: localhost
    migrations_paths: db/ro

production:
  primary:
    <<: *default
    database: personal_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
  ryan_romanchuk:
    <<: *default
    database: ryan_romanchuk_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/ryan_romanchuk
  wx:
    <<: *default
    database: wx_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/wx
    adapter: postgis
    schema_search_path: public, postgis
  ro:
    <<: *default
    database: ro_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV['DATABASE_HOST'] %>
    migrations_paths: db/ro
  cache:
    adapter: sqlite3
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache
  cable:
    adapter: sqlite3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable
