default: &default
  title: Ryan Romanchuk
  auth_url: https://auth.romanch.uk
  apex_url: https://romanch.uk
  cognito_redirect: https://romanch.uk/oauth2/idpresponse
  my_id: 54467d4a-f7bc-457d-aa72-55842106b02e

production:
  <<: *default
  romanchukopen_host: romanchukopen.com
  romanchuk_host: romanch.uk

development:
  <<: *default
  apex_url: https://personal.test
  cognito_redirect: https://personal.test/oauth2/idpresponse
  romanchukopen_host: romanchukopen.test
  romanchuk_host: personal.test