# rubocop:disable Metrics/ModuleLength

module Wx
  module Constants
    TEI_DICTIONARY = {
      '-': 'Light', # intensity, except when associated with LLWS',
      '+': 'Heavy', # intensity',
      # '/': 'Solidus. Separator between cloud layers, layers of turbulence, or layers of icing',
      ABV: 'Above',
      AC: 'Altocumulus Cloud(s)',
      ACC: 'Altocumulus Castellanus Cloud(s)',
      'ACFT MSHP': 'Aircraft Mishap',
      ACSL: 'Standing Lenticular Altocumulus Castellanus Cloud(s)',
      APCH: 'Approach',
      APRNT: 'Apparent',
      APRX: 'Approximate',
      ATCT: 'Air Traffic Control Tower',
      B: 'Becoming',
      BC: 'Patches', # (descriptor used with FG)',
      BKN: 'Broken', # (used to describe cloud cover or weather phenomena)',
      BL: 'Blowing', # (descriptor used with DU, SA, or SN)',
      BLO: 'Below',
      BR: 'Mist',
      CA: 'Cloud to air (lightning)',
      CAS: 'Committee for Aviation Services',
      CAT: 'Clear Air Turbulence',
      CB: 'Cumulonimbus Cloud(s)',
      CBMAM: 'Cumulonimbus Mammatus Cloud(s)',
      CC: 'Cirrocumulus Cloud(s)',
      CCSL: 'Standing Lenticular Cirrocumulus Cloud(s)',
      CG: 'Cloud to ground (lightning)',
      CHOP: 'Chop',
      CIG: 'Ceiling',
      CLR: 'Clear', # Clear (Icing) - a type of glossy, clear, or translucent ice, or  (Sky condition) - the absence of clouds reported by an automated weather reporting station
      CONS: 'Continuous',
      CONTRAILS: 'Condensation trails', #--ice vapor trails created by high-flying aircraft',
      CS: 'Cirrus Cloud(s)',
      CTC: 'Contact',
      DR: 'Drifting', # (descriptor used with DU, SA, or SN)
      DS: 'Duststorm',
      DSNT: 'Distant',
      DU: 'Widespread Dust',
      DURGC: 'During Climb',
      DURGD: 'During Descent',
      DZ: 'Drizzle',
      E: 'East',
      EMBD: 'Embedded',
      ENE: 'East-northeast',
      ENRT: 'Enroute',
      EST: 'Estimated',
      EXTRM: 'Extreme',
      FAA: 'Federal Aviation Administration',
      FC: 'Funnel Cloud(s)',
      '+FC': 'Tornado',
      FEW: 'Few', # (used to describe cloud cover or weather phenomena)
      FG: 'Fog',
      FRQ: 'Frequent',
      FT: 'Feet',
      FU: 'Smoke',
      FV: 'Flight Visibility',
      FZ: 'Freezing',
      G: 'Gusting',
      GND: 'Ground',
      GR: 'Hail',
      GS: 'Snow pellets',
      HLSTO: 'Hailstone',
      HVY: 'Heavy',
      HZ: 'Haze',
      IC: 'Ice Crystals',
      ICAO: 'International Civil Aviation Organization',
      IMC: 'Instrument Meteorological Conditions',
      INCRG: 'Increasing',
      INTMT: 'Intermittent',
      ISOL: 'Isolated',
      KT: 'Knots',
      LGT: 'Light',
      LLWS: 'Low Level Wind Shear',
      LN: 'Line',
      LST: 'Local Standard Time',
      LTG: 'Lightning',
      LTGCA: 'Cloud to air',
      LTGCC: 'Cloud to cloud',
      LTGCG: 'Cloud to ground',
      LTGIC: 'Intracloud',
      LYR: 'Layer',
      LWR: 'Lower',
      M: 'Sub-zero temperature',
      METAR: 'Meteorological Aerodrome Report',
      MI: 'Shallow',
      MOD: 'Moderate',
      MOV: 'Moving',
      MSL: 'Mean Sea Level',
      MT: 'Mountains',
      MX: 'Mixed',
      N: 'North',
      NAVAID: 'Navigation Aid',
      NE: 'Northeast',
      NMRS: 'Numerous',
      NW: 'Northwest',
      OCNL: 'Occasional',
      OFCM: 'Office of the Federal Coordinator for Meteorology',
      OVC: 'Overcast (used to describe cloud cover or weather phenomena)',
      OVR: 'Over',
      PCPN: 'Precipitation',
      PIREP: 'Pilot Report',
      'PK WND': 'Peak Wind',
      PL: 'Ice Pellets',
      PO: 'Dust/sand whirls',
      PR: 'Partial',
      PY: 'Spray',
      RA: 'Rain',
      RCA: 'Reach Cruising Altitude',
      RIME: 'Rime', # Type of Icing characterized by a rough, milky, opaque appearance
      RY: 'Runway',
      S: 'South',
      SA: 'Sand',
      SCSL: 'Standing Lenticular Cirrus Cloud(s)',
      SCT: 'Scattered', # (used to describe cloud cover or weather phenomena)',
      SE: 'Southeast',
      SEV: 'Severe',
      SFC: 'Surface',
      SG: 'Snow Grains',
      SH: 'Showers',
      SKC: 'Sky Clear',
      SLD: 'Solid',
      SM: 'Statute Mile',
      SN: 'Snow',
      SP: 'Snow Pellets',
      SPECI: 'Aviation Wewather Special Report',
      SQ: 'Squalls',
      SS: 'Sandstorm',
      STN: 'Station',
      SW: 'Southwest',
      TACAN: 'Tactical Air Navigation',
      TCU: 'Towering Cumulus Cloud(s)',
      TEI: 'Text Element Identifier',
      TOC: 'Top of Climb',
      TOP: 'Top of Clouds',
      TS: 'Thunderstorm',
      UA: 'Routine Report', # Text Element Indicator for a Routine Pilot Report (PIREP)
      UNKWN: 'Unknown',
      UP: 'Unknown Precipitation',
      UTC: 'Coordinated Universal Time',
      UUA: 'Urgent Report', # Text Element Indicator for an Urgent Pilot Report (PIREP)
      VA: 'Volcanic Ash',
      VC: 'In Vicinity',
      VHF: 'Very High Frequency',
      VIS: 'Visibility',
      VMC: 'Visual Meteorological Conditions',
      VOR: 'VHF Omnidirectional Range',
      VORTAC: 'VHF Omnidirectional Range/Tactical Air Navigation',
      VRB: 'Variable',
      W: 'West',
      WMO: 'World Meteorological Organization',
      WND: 'Wind',
      Z: 'Zulu Time'
    }.with_indifferent_access
  end
end
